DROP TABLE BOARD;
CREATE TABLE BOARD (
	IDX NUMBER PRIMARY KEY,
	WRITER VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000),
	CREATED DATE
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO BOARD VALUES (9999, '관리자', '공지사항', '공지사항내용', SYSDATE);
COMMIT;
